### ISSUE TITLE
feat: Add shadow effects 

### ISSUE THREAD

**Issue by dhirajchaurasiya** [dhirajchaurasiya/Portfolio-website#18]
**Description**
Add shadow effects to cards of `Interest and Skill` section similar to cards of  `About Me` section.

**Comment by ATHARVA-MUJUMDAR** [comment]
@dhirajchaurasiya10 please assign this to me. 
Thank you.

**Comment by dhirajchaurasiya** [comment]
@ATHARVA-MUJUMDAR you are assigned. Happy contributing.
