### ISSUE TITLE
feat: Add Linkedin Icon to the Intro section

### ISSUE THREAD

**Issue by dhirajchaurasiya** [dhirajchaurasiya/Portfolio-website#2]
**Description**
The Profile Section in the website lacks LinkedIn Icon. 

**ToDo**
Add LinkedIn Icon alongside other social media handles icon.

**Screenshots**
![image](https://github.com/user-attachments/assets/3e5d0c1d-616d-428b-a247-eaf8a0e8ccb3)

**Steps to Reproduce**
- Go to https://www.dhirajchaurasiya.com.np
- Navigate to social media icons.

Ready to Work?
- [ ] I want to work on this issue

**Comment by SubediBinod** [comment]
Assign me, maile garxu

**Comment by BURNOUTAlGO** [comment]
Assighn this task to me

**Comment by dhirajchaurasiya** [comment]
Sorry this has been closed.  Stay updated while I raise other issues, or you can also raise issue to my other repo.
