### ISSUE TITLE
Replace Whatsapp with Linkedin in Contact Section

### ISSUE THREAD

**Issue by dhirajchaurasiya** [dhirajchaurasiya/Portfolio-website#5]
**Description**
- The Contact section of the website has Mail and Whatsapp. Replace the Whatsapp portion with Linkedin

![image](https://github.com/user-attachments/assets/6dee1990-df19-435a-b448-856b42632482)

**Expected Behaviour**
![image](https://github.com/user-attachments/assets/bd14b70e-a6c2-41e1-84b9-933c8bcdc40a)

**How to Contribute**
- Fork the Repo and clone it.
- Make the changes and push it.
- Compare and create a pull request
- Add suitable title for the issue you solved.
- Describe what changes you did and it's effect in the description box.
- Mention the issue you solved and create PR.

**Comment by DinukaUdawela** [comment]
Can you please assign me to the task

**Comment by DeathwingIN** [comment]
can u assign me to this

**Comment by askarthikey** [comment]
Heyy @dhirajchaurasiya10 I would like to work on this issue. Can you please assign me this
