### ISSUE TITLE
Add shadow effects to the Cards

### ISSUE THREAD

**Issue by dhirajchaurasiya** [dhirajchaurasiya/Portfolio-website#7]
**Desciption**
- Add few styling to the cards in **About Section** by applying shadow effect to the cards.

**Comment by SubediBinod** [comment]
assign me

**Comment by SubediBinod** [comment]
Assign me ,  I am committed to completing the work by tomorrow. XD

**Comment by dhirajchaurasiya** [comment]
Needs more changes to get it fixed.
@SubediBinod you're already assigned. Go for it

**Comment by BaniSinghgithub** [comment]
hello sir @dhirajchaurasiya10  , pls assign this work to me.
